package com.ibm.btt.application.op;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;

/**
 * Class Generated by BTT Tool Created since: 2012/09/18 11:04:01
 */
public class CreatePaginationData extends BTTServerOperation
{
	private int rowsPerPage;
	private int total;
	private int pageNumber;
	private int toSavePageNumber;
	private int pageSize;
	private int toSaveBeginCount;
	private int toSaveEndCount;
	private int beginCount;
	private int endCount;
	private boolean pagination;

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public void execute() throws Exception
	{

		Context ctx = getContext();
		KeyedCollection opData = this.getContext().getKeyedCollection();
		IndexedCollection accountTable = (IndexedCollection) opData.getElementAt("AccountInfoList");
		
		Object o = ctx.getValueAt("paginationData");

		if (o == null)
			this.pagination = false;
		else
			this.pagination = true;

		if (pagination)
		{
			rowsPerPage = (Integer) ctx.getValueAt("paginationData.rowsPerPage");
			pageNumber = (Integer) ctx.getValueAt("paginationData.pageNumber");
			toSavePageNumber = (Integer) opData.getValueAt("currentPageNum");
			total = (Integer) ctx.getValueAt("paginationData.totalRowNumber");

			pageSize = total / rowsPerPage;
			if (total % rowsPerPage > 0)
			{
				pageSize++;
			}

			// beginCount
			beginCount = (pageNumber - 1) * rowsPerPage;

			// toSaveBeginCount
			toSaveBeginCount = (toSavePageNumber - 1) * rowsPerPage;

			// endCount
			if (pageNumber == pageSize)
			{
				endCount = total;
			}
			else
			{
				endCount = pageNumber * rowsPerPage;
			}

			// toSaveEndCount
			if (toSavePageNumber == pageSize)
				toSaveEndCount = total;
			else
				toSaveEndCount = toSavePageNumber * rowsPerPage;

			ctx.setValueAt("paginationData.totalRowNumber", total);
			ctx.setValueAt("paginationData.pageNumber", pageNumber);

			if (pageNumber <= 1)
			{
				ctx.setValueAt("paginationData.enableNext", "true");
				ctx.setValueAt("paginationData.enablePrevious", "false");
			}
			else if (pageNumber == pageSize)
			{
				ctx.setValueAt("paginationData.enableNext", "false");
				ctx.setValueAt("paginationData.enablePrevious", "true");
			}
			else
			{
				ctx.setValueAt("paginationData.enableNext", "true");
				ctx.setValueAt("paginationData.enablePrevious", "true");
			}
		}

		System.out.println("accountTable is : -----------------------------------------------------------------------------------------------------");
		System.out.println(accountTable.toString());
		System.out.println("accountTable is : -----------------------------------------------------------------------------------------------------");
		
		// save changed value
		AccountListDB.saveAccountList(accountTable, toSavePageNumber);

		// set value		
		AccountListDB.getAllAccountList(pageNumber, accountTable);
		
		fireExitEvent("ok");
	}
}
