package com.ibm.btt.application.op;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;

/**
 * Class Generated by BTT Tool Created since: 2012/09/18 11:04:01
 */
public class CreatePaginationData extends BTTServerOperation {
	private int rowsPerPage;
	private int total;
	private int pageNumber;
	private int pageSize;
	private int beginCount;
	private int endCount;
	
	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public void execute() throws Exception {
		
		Context ctx = getContext();
		rowsPerPage =(Integer)ctx.getValueAt("paginationData.rowsPerPage");
		pageNumber = (Integer)ctx.getValueAt("paginationData.pageNumber");
		total = (Integer)ctx.getValueAt("paginationData.totalRowNumber");

		pageSize = total / rowsPerPage;
		if (total % rowsPerPage > 0) {
			pageSize++;
		}
		//beginCount
		if (pageNumber == 1) {
			beginCount = 0;
		}else{
			beginCount = (pageNumber-1) * rowsPerPage;
		}
		//endCount
		if (pageNumber == pageSize) {
			endCount = total;
		}else{
			endCount = pageNumber * rowsPerPage;
		}	
		ctx.setValueAt("paginationData.totalRowNumber", total);
		ctx.setValueAt("paginationData.pageNumber", pageNumber);

		if (pageNumber <= 1) {
			ctx.setValueAt("paginationData.enableNext", "true");
			ctx.setValueAt("paginationData.enablePrevious", "false");
		} else if (pageNumber == pageSize) {
			ctx.setValueAt("paginationData.enableNext", "false");
			ctx.setValueAt("paginationData.enablePrevious", "true");
		} else {
			ctx.setValueAt("paginationData.enableNext", "true");
			ctx.setValueAt("paginationData.enablePrevious", "true");
		}
		
		KeyedCollection opData = this.getContext().getKeyedCollection();
		IndexedCollection accountTable = (IndexedCollection) opData.getElementAt("AccountInfoList");
		for (int i = 0; i < rowsPerPage; i++) {
			accountTable.setValueAt(i + ".AccountName", "Helen" + (beginCount+i));
		}
		//String pageEvent =ctx.getValueAt("paginationData.pageEvent")!=null?ctx.getValueAt("paginationData.pageEvent").toString():"";
		//if ("".equals(pageEvent)) {
			
			fireExitEvent("ok");
		//}
	}
}
