/*_
 * Licensed Materials - Property of IBM
 * Restricted Materials of IBM
 * 5724-H82
 * (C) Copyright IBM Corp. 2011 All Rights Reserved.
 * US Government Users Restricted Rights - Use, duplication or disclosure
 * restricted by GSA ADP Schedule Contract with IBM Corp
 */
package com.ibm.btt.application.op;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.ContextFactory;

/**
 * Class Generated by BTT Tool Created since: 2010/12/13 17:36:42
 */
public class StartUpOp extends BTTServerOperation {
	@SuppressWarnings("unused")
	private static final java.lang.String COPYRIGHT = "Licensed Materials - Property of IBM "//$NON-NLS-1$
			+ "Restricted Materials of IBM "//$NON-NLS-1$
			+ "5724-H82 "//$NON-NLS-1$
			+ "(C) Copyright IBM Corp. 2008, 2010 All Rights Reserved. "//$NON-NLS-1$
			+ "US Government Users Restricted Rights - Use, duplication or disclosure "//$NON-NLS-1$
			+ "restricted by GSA ADP Schedule Contract with IBM Corp ";//$NON-NLS-1$
	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public void execute() throws Exception {
		System.out.println("StartUpOp");
		Context root = ContextFactory.getRoot();
		
		if (root == null) {
			System.out.println("Creating root ctx");
			root = ContextFactory.createContext("branchServer");
		}
		
		Context sessionCtx = ContextFactory.createContext("sessionCtx");
		sessionCtx.chainTo(root);

		this.getContext().chainTo(sessionCtx);

	}
}
