({
"AccountBlance":"AccountBlance",
"Rate":"Rate",
"AccountOpeningDate":"AccountOpeningDate",
"TradeTimeForSelect":"TradeTimeForSelect",
"Usable":"Usable",
"TradeTime":"TradeTime",
"AccountName":"AccountName",
"MaximumAmount":"MaximumAmount"})
