({
"TradeTime":"TradeTime",
"accountAttribution":"accountAttribution",
"Image":"Image",
"Usable":"Usable",
"AccountName":"AccountName",
"Localtion":"Localtion",
"AccountOpeningDate":"AccountOpeningDate",
"AccountBlance":"AccountBlance",
"TradeTimeValue":"TradeTimeValue",
"MaximumAmount":"MaximumAmount",
"AccountType":"AccountType",
"AccountTypeValue":"AccountTypeValue",
"Rate":"Rate"})
